---
title: "Assignment"
author: ""
date: today
output: html_document
params:
  season: 1
---

```{python}
import pandas as pd
season = params['season']
df = pd.read_csv('Data/got/season_{season}.csv')

episode_count = df.shape[0]

df['premiere_date'] = pd.to_datetime(df['premiere_date'].apply(lambda x: re.search(r'(\d{4}-\d{2}-\d{2})', x).group(1)))
first_premdate = df['premiere_date'].min().strftime('%B %d, %Y')
last_premdate = df['premiere_date'].max().strftime('%B %d, %Y')

average_viewer = df['viewers'].mean()
first_episode_viewer = df.iloc[0]['viewers']
last_episode_viewer = df.iloc[-1]['viewers']

max_viewer_index = df['viewers'].idxmax()
max_viewer_title = df.loc[max_viewer_index, 'title']
max_viewer_description = df.loc[max_viewer_index, 'description']
```

# Game of Thrones - Season {season} summary in numbers

### __(*Warning:* spoilers ahead)__

***

### Overview

(From the [Wikipedia](https://en.wikipedia.org/wiki/Game_of_Thrones#Premise)) Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones.

Set on the fictional continents of Westeros and Essos, Game of Thrones has a large ensemble cast and follows several story arcs throughout the course of the show. A major arc concerns the Iron Throne of the Seven Kingdoms of Westeros through a web of political conflicts among the noble families either vying to claim the throne or fighting for independence from it. Another focuses on the last descendant of the realm's deposed ruling dynasty, who has been exiled to Essos and is plotting a return to the throne. A third story arc follows the Night's Watch, a military order defending the realm against threats from the North.

***

### Season {season} summary

Season {season} of Game of Thrones consisted of {{episode_count}} episodes that aired between {{first_premdate}} and {{last_premdate}} on HBO. The show gathered an average of {{average_viewer}} first-day TV viewers in the US, with the number changing from {{first_episode_viewer}} to {{last_episode_viewer}} million by the end of the season.

The most popular episode of the season was "{{max_viewer_title}}", in which:

> "{{max_viewer_description}}"

***

You can see how the viewership of the episodes changed in Figure 1.

```{python}
import matplotlib.pyplot as plt

colors = ['red' if viewers > average_viewer else 'green' for viewers in df['viewers']]
plt.bar(df['no_season'], height=df['viewers'], color=colors)
plt.xlabel('Episode number')
plt.ylabel('1st day TV viewers in the US (millions)')
plt.title(f'Viewer Count for Season {season}')
plt.show()
```

***

Finally, the episodes with the above-average viewership were:

```{python}
high_viewer_episodes = df[df['viewers'] > average_viewer][['no_season', 'title', 'directed_by']]
table_str = ""
for index, row in high_viewer_episodes.iterrows():
    table_str += f"| {row['no_season']} | {row['title']} | {row['directed_by']} |\n"
```

| No. in season | Title  | Directed by  |
|:------        |:-----: |:------:      |
{{table_str}}
